---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "default/brewz-api-security-policy"
    securityLog:
      enable: true
      apLogConf: "default/logconf"
      logDest: "syslog:server=logging-fluentd.monitoring.svc.cluster.local:5140"
